runtime:
  cache_dir: ./.cache/antora
site:
  title: Asciidoctor Docs
  url: https://docs.asciidoctor.org
  start_page: asciidoctor::index.adoc
  robots: allow
git:
  ensure_git_suffix: false
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: current
content:
  sources:
  - url: https://github.com/asciidoctor/asciidoc-docs
    branches: main
  - url: https://github.com/graphitefriction/asciidoctor
    branches: issue-3861-import-docs
    start_path: docs
  - url: https://github.com/asciidoctor/asciidoctor.js
    branches: master
    start_path: docs
  - url: https://github.com/asciidoctor/asciidoctor-cli.js
    branches: master
    start_path: docs
  - url: https://github.com/asciidoctor/asciidoctor-community-docs
    branches: main
  - url: https://github.com/asciidoctor/asciidoctor-maven-plugin
    branches: master
    start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    table-caption: false
    table-frame: 'none@'
    table-grid: 'rows@'
    example-caption: false
    listing-caption: false
    hide-uri-scheme: '@'
    url-project: https://asciidoctor.org
    url-org: https://github.com/asciidoctor
  extensions:
  - ./lib/collapsible-block-tree-processor.js
  - ./lib/global-table-attributes-tree-processor.js
ui:
  bundle:
    url: https://github.com/asciidoctor/docs.asciidoctor.org-ui/releases/download/prod-33/ui-bundle.zip
output:
  dir: ./public
